"""
Django settings for my_site project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#项目基本文件夹
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',#所有的模型都会记录在这个contenttypes
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',  # 富文本编辑器app
    'ckeditor_uploader',  # 富文本图片上传的app
    'blog',#博客app
    'read_statistics',
    'comment',
    'likes',
    'user',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates')
        ],#全局模板文件夹templates
        'APP_DIRS': True,#有效
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.login_modal_form',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_site.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#部署后收集静态文件路径
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')

STATIC_URL = '/static/'
#指定静态文件路径
STATICFILES_DIRS =[
    os.path.join(BASE_DIR, 'static'),
]

# 让authenticate不关联is_active
#AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

#富文本编辑器使用
#media,保存博客上传的图片等文件的路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
#配置ckeditor（富文本编辑器的）
CKEDITOR_UPLOAD_PATH = 'upload/'

#ckeditor配置
CKEDITOR_CONFIGS = {
    'default':{},#这里的默认是后台的
    'comment_ckeditor': {#comment_ckeditor是前端评论时候的富文本编辑器
        'toolbar':'custom',
        'toolbar_custom':[
            ['Bold', 'Italic', 'Underline','Strike','Subscript','Superscript'],
			['TextColor','BGColor','RemoveFormat'],
			['NumberedList', 'BulletedList'],
			['Link', 'Unlink'],
            ['Smiley','SpecialChar','Blockquote'],
			['CodeSnippet']
        ],
		'width':'auto',
        'height':'150',
        'tabSpaces': 4,
		'removePlugins':'elementspath',
		'resize_enabled':False,
        # 插件
        'extraPlugins': ','.join(['codesnippet','lineutils']),
    }
}

#自定义参数
EACH_PAGE_BLOGS_NUMBER = 7  #分页时候每页的博客文章数量


#数据库高速缓存,
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}
#发送邮件设置
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.qq.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'wqz_blog@qq.com'    #发送人
# EMAIL_HOST_PASSWORD = "ntlgbvbigjaldigi"    #授权码
# EMAIL_USE_SSL = True    #与SMTP服务器通信时是否使用TLS（安全）连接
# EMAIL_SUBJECT_PREFIX = '[wqz的博客]'   #发送的电子邮件的主题行前缀
